name: 'Customized cfn-lint action for AWS Quick Start org use'
author: 'Andrew Glenn'

branding:
  icon: 'file-text'
  color: 'green'

inputs:
  program:
    description: "cfnlint"
    required: true
    default: 'cfn-lint -a team_custom_rules checked_out_repo/templates/*'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.program }}

outputs:
  time:
    description: 'Action Completed'
